<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <?php $this->getMesseger(); ?>
           
            <?php if (isset($this->usuario) && !empty($this->usuario)) { ?>
                <table class="artist-photo">
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: #EBEBEB;">
                            <div style="padding-left: 5px;float: left;color: #0154A0" >
                                <img  src="<?php echo MEDIA_URL ?>img/portalwap/ico-miEntel.png"/>  [ <?php echo $this->usuario ?>  ]
                            </div>
                        </td>
                    </tr>  </table><br>

            <?php } ?>
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                <link href="<?php echo MEDIA_URL ?>css/wap/estilogGeneral.css"
                      rel="stylesheet" type="text/css" media="all" />
                <!----------------SLIDER DE LOS BANNER PRINCIPALES------------------------------------->
                <script type="text/javascript" src="<?php echo MEDIA_URL ?>js/avanzado/jquery.carouFredSel-6.2.1-packed.js"></script>
                <script type="text/javascript" src="<?php echo MEDIA_URL ?>js/avanzado/jquery.touchwipe.min.js"></script>
                <script type="text/javascript" src="<?php echo MEDIA_URL ?>js/avanzado/homeBase.js"></script>
                <div class="clearfix cajaDesctacado">
                    <a href="#" id="hdFlechaIzq" class="hdFlechaIzq"><img src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/slider/imgDestacadoFlechaIzq.png" alt="" ></a>
                    <a href="#" id="hdFlechaDer" class="hdFlechaDer"><img src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/slider/imgDestacadoFlechaDer.png" alt="" ></a>
                    <ul class="homeDestacado clearfix" id="homeDestacado">
                        <li>    
                            <a href="/go?link=http://entel.bip.pe/pe/realtones">
                                <img src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/slider/banner_tonos_nextel.gif" alt="Promociones Hogar" >
                            </a>
                        </li>
                        <li>    
                            <a href="/go?link=http://entel.bip.pe/pe/fulltracks" >
                                <img src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/slider/banner-musica-nextel.gif" alt="hogar C2C" >
                            </a>
                        </li>
                        <li>    
                            <a href="/go?link=/dedicatoria">
                                <img  src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/slider/banner_dedicatorias_nextel.gif" alt="PROMO PORTABILIDAD" >
                            </a>
                        </li>
                        <li>    
                            <a href="/go?link=http://mobile.terra.com/sc/pe/suscfutentel/" >
                                <img src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/slider/banner_futbol.gif" alt="Packs" >
                            </a>
                        </li>

                    </ul>
                    <div class="hdPagination">&nbsp;</div>
                </div>
                <!----------------SERVICIOS------------------------------------>
                <div id="cabecera-listado" class="clearfix">
                    <a id="cabecera_paso1" class="paso primero seleccionado" href="#" style="background:no-repeat scroll right center rgb(221, 221, 221);">
                        <span class="textos clearfix">
                            <span class="titulo">Enlaces de Interes</span>
                        </span>
                    </a>
                </div>                     

                <!------------------------------- SERVICIOS    ------------------------------>
                <table class="artist-photo">
                    <tr>
                        <td class="">
                            <div>
                                <a href="/go?link=https://www.google.com.pe"><img     class="img-iconos"
                                                                                      src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/google.png">
                                </a>
                            </div>
                        </td>
                        <td class="">
                            <div>
                                <a href="/go?link=https://m.facebook.com/"><img class="img-iconos"
                                                                                src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/facebook.png">
                                </a>
                            </div>
                        </td>
                        <td class="">
                            <div>
                                <a href="/go?link=https://mobile.twitter.com/"> <img class="img-iconos"
                                                                                     src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/twitter.png">
                                </a>
                            </div>
                        </td>
                        <td class="">
                            <div>
                                <a href="/go?link=https://www.youtube.com"> <img class="img-iconos"
                                                                                 src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/youtube.png">
                                </a>
                            </div>
                        </td>
                        <td class="">
                            <div>
                                <a href="/go?link=http://elcomercio.pe/movil/"> <img class="img-iconos"
                                                                                     src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/comercio.png">
                                </a>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="">
                            <div>
                                <a href="/go?link=https://mail.google.com/"> <img class="img-iconos"
                                                                                  src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/gmail.png">
                                </a>
                            </div>
                        </td>
                        <td class="">
                            <div>
                                <a href="/go?link=https://login.live.com/"><img class="img-iconos"
                                                                                src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/hotmail.png">
                                </a>
                            </div>
                        </td>
                        <td class="">
                            <div>
                                <a href="/go?link=http://es.m.wikipedia.org/wiki/Main_Page">  <img class="img-iconos"
                                                                                                   src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/wikipedia.png">
                                </a>
                            </div>
                        </td>
                        <td class="">
                            <div>
                                <a href="/go?link=https://www.linkedin.com/uas/login"> <img class="img-iconos"
                                                                                            src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/linkedin.png">
                                </a>
                            </div>
                        </td>
                        <td class="">
                            <div>
                                <a href="/go?link=http://www.terra.com/"> <img class="img-iconos"
                                                                               src="<?php echo MEDIA_URL ?>img/portalwap/avanzado/servicios/cartelera.png">
                                </a>
                            </div>
                        </td>
                    </tr>
                </table>
                <!------------------------------- SERVICIOS    ------------------------------>

                <br>
                <!----------------MUSICA TOP------------------------------------->
                <div id="cabecera-listado" class="clearfix">
                    <a id="cabecera_paso1" class="paso primero seleccionado" href="" style="background:no-repeat scroll right center rgb(221, 221, 221);">
                        <span class="textos clearfix">
                            <span class="bullet">1</span>
                            <span class="titulo">M&uacute;sica Top</span>
                        </span>
                    </a>
                </div> 


                <table class="artist-photo">
                    <tr>
                        <?php
                        $i = 0;
                        foreach ($this->SoapMusica as $item):
                            $i++;
                            ?>
                            <td class="artist">
                                <div class="artist-text">
                                    <a class="text-title"
                                       href="/go?link=http://entel.bip.pe/pe/fulltracks/?catalogo=<?= strtoupper($item->catalogo) ?>"><div>
                                               <?php
                                               $nombre_fichero = APPLICATION_PATH . '/../public/static/img/portalwap/basico360/musica/' . $item->catalogo . '.jpg';
                                               if (file_exists($nombre_fichero)) {
                                                   ?>
                                                <img class="img-icono" src="<?php echo MEDIA_URL ?>img/portalwap/basico360/musica/<?= $item->catalogo ?>.jpg"  />
                                            <?php } else {
                                                ?>
                                                <img class="img-icono" src="<?php echo MEDIA_URL ?>img/portalwap/basico360/musica/default.gif"  border="0" />

                                            <?php }
                                            ?> </div>
                                        <div class="title-img">
                                            <?= strtoupper($item->tema) ?>
                                        </div> </a>
                            </td>
                            <?php
                        endforeach;
                        ?>
                    </tr>
                    <tr>
                        <td class="artist"  colspan=5 style="background-color:#F68E1F;height: 12px ">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="text-decoration: underline;float: right;color: white;font-size:18px"
                                       href="/go?link=http://entel.bip.pe/pe/fulltracks">Suscr&iacute;bete
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <br>
                <!----------------TONOS------------------------------------->
                <div id="cabecera-listado" class="clearfix">
                    <a id="cabecera_paso1" class="paso primero seleccionado" href="#" style="background:no-repeat scroll right center rgb(221, 221, 221); ">
                        <span class="textos clearfix">
                            <span class="bullet">2</span>
                            <span class="titulo">Tonos</span>
                        </span>
                    </a></div>

                <table class="artist-photo">
                    <tr>
                        <?php
                        $i = 0;
                        foreach ($this->SoapTonos as $item):
                            $i++;
                            ?>

                            <td class="artist">
                                <div class="artist-text">
                                    <a class="text-title" href="/go?link=http://entel.bip.pe/pe/realtones/?catalogo=<?= strtoupper($item->catalogo) ?>"><div>
                                            <?php
                                            $nombre_fichero = APPLICATION_PATH . '/../public/static/img/portalwap/basico360/tonos/' . $item->catalogo . '.jpg';
                                            if (file_exists($nombre_fichero)) {
                                                ?>
                                                <img class="img-icono" src="<?php echo MEDIA_URL ?>img/portalwap/basico360/tonos/<?= $item->catalogo ?>.jpg"  />
                                            <?php } else {
                                                ?>
                                                <img class="img-icono" src="<?php echo MEDIA_URL ?>img/portalwap/basico360/tonos/default.gif"  border="0" />

                                            <?php }
                                            ?> </div>
                                        <div class="title-img">
                                            <?= strtoupper($item->tema) ?>
                                        </div> </a>
                                </div>
                            </td>
                            <?php
                        endforeach;
                        ?>
                    </tr>
                    <tr>
                        <td class="artist"  colspan=5 style="background-color:#F68E1F;height: 12px ">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="text-decoration: underline;float: right;color: white;font-size:18px"
                                       href="/go?link=http://entel.bip.pe/pe/realtones">Suscr&iacute;bete
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <br>
            </div>
        </div>
    </div>
</div>
<?php
if (empty($this->usuario) && !isset($this->usuario) && $this->perfil != '240') {

    if (isset($this->numero) && $this->numero != '') {
        ?>
        <script>
            $(document).ready(function () {
                centraVentana();
                muestraVentana();
                $("#ventanaPopup1Cerrar").click(function () {
                    ocultaVentana();
                });
                $("#ventanaPopup1Fondo").click(function () {
                    ocultaVentana();
                });
            });

            function centraVentana() {
                var windowWidth = document.documentElement.clientWidth;
                var windowHeight = document.documentElement.clientHeight;
                var popupHeight = $("#ventanaPopup1").height();
                var popupWidth = $("#ventanaPopup1").width();
                $("#ventanaPopup1").css({
                    "position": "absolute",
                    //            "top": windowHeight / 2 - popupHeight / 2,
                    //            "left": windowWidth / 2 - popupWidth / 2
                });
                $("#ventanaPopup1Fondo").css({
                    "height": windowHeight
                });
            }
            function ocultaVentana() {
                $("#ventanaPopup1Fondo").fadeOut("slow");
                $("#ventanaPopup1").fadeOut("slow");
            }

            function muestraVentana() {
                $("#ventanaPopup1Fondo").css({
                    "opacity": "0.7"
                });
                $("#ventanaPopup1Fondo").fadeIn("slow");
                $("#ventanaPopup1").fadeIn("slow");
            }
        </script>
        <?php
    }
}
?>
<style type="text/css">
    #ventanaPopup1Fondo{
        display:none;
        position:fixed;
        _position:absolute; /* caso especial para IE 6*/
        height:100%;
        width:100%;
        top:0;
        left:0;
        background:#000000;
        z-index:1;
    }
    #ventanaPopup1{
        border:4px solid #0154A0;
        top:20px;
        margin: 0px 18px 10px 23px;
        display:none;
        position:fixed;
        _position:absolute; /* caso especial para IE 6*/
        /*height:384px;*/
        /*width:408px;*/
        background:#FFFFFF;
        z-index:2;
        padding:12px;
        font-size:13px;
        /*border:5px solid #888888;*/

        /*border-radius:10px;*/
        -moz-border-radius:10px;
    }
    #ventanaPopup1Cerrar{
        font-size:14px;
        line-height:14px;
        right:2px;
        top:4px;
        position:absolute;
        color:#6fa5fd;
        font-weight:700;
        display:block;
        cursor: hand;
        
    }
    #form
    {

        margin:auto;
        font-family: sans-serif;
        /*box-shadow: 5px 5px 5px #888888;*/
        padding: 2px 20px 20px  20px;
        /*border:4px solid #27748A;*/
    }
    #form h2
    {
        color:#27748A;
        font-size:35px;
        margin:0;
    }
    #form p
    {
        font-size:15px;
        color:#222222;
    }

    #form div
    {
        margin-top:10px;
    }
    #form input, textarea, button,select,radio
    {
        width:100%;
        border:2px solid #EBEBEB;
        padding:3px 5px;
    }
    #form label
    {
        font-weight:bold;
        font-size:12px;
        color:#0154A0;
    }

    #form button
    {
        background-color: #FF6702;
        border:2px solid #FF6702;
        color: white;
        cursor:pointer;
    }
    #form button:hover
    {
        background-color: #0154A0;
        border:2px solid #0154A0;
        color: white;
    }
    .dia{width: 50px; float: left; margin-right: 5px;list-style:none;}
    .mes{width: 80px; float: left; margin-right: 5px;list-style:none;}
    .ano{width: 60px; float: left;list-style:none;}
</style>
