<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
                      <?php $this->getMesseger(); ?>         
                <?php if (isset($this->usuario) && !empty($this->usuario)) { ?>
                    <table class="artist-photo">
                        <tr>
                            <td class="artist"  colspan=2 style="background-color: #EBEBEB;">
                                <div style="padding-left: 5px;float: left;color: #0154A0" >
                                    <img  src="<?php echo MEDIA_URL ?>img/portalwap/ico-miEntel.png"/>  [ <?php echo $this->usuario ?>  ]
                                </div>
                            </td>
                        </tr>  </table><br>

                <?php } ?>
                <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                    <!----------------BANNER DE DEDICATORIA------------------------------------->
                    <div>
                        <a href="/go?link=http://entel.bip.pe/pe/realtones">
                            <img width="100%" src="<?php echo MEDIA_URL ?>img/portalwap/basico360/slider/banner_tonos_nextel.gif">
                        </a>
                    </div>
                    <div>
                        <a href="/go?link=http://entel.bip.pe/pe/fulltracks">
                            <img width="100%" src="<?php echo MEDIA_URL ?>img/portalwap/basico360/slider/banner-musica-nextel.gif">
                        </a>
                    </div>
                    <div> 
                        <a href="/go?link=/dedicatoria">
                            <img width="100%" src="<?php echo MEDIA_URL ?>img/portalwap/basico360/slider/banner_dedicatorias_nextel.gif">
                        </a>
                    </div>
                    <div> 
                        <a href="/go?link=http://mobile.terra.com/sc/pe/suscfutentel/">
                            <img width="100%" src="<?php echo MEDIA_URL ?>img/portalwap/basico360/slider/banner_futbol.gif">
                        </a>
                    </div>
                    <!----------------BUSCADORES DESTACADOS------------------------------------->
                    <div id="cabecera-listado" class="clearfix">
                        <a id="cabecera_paso1" class="paso primero seleccionado" href="" style="background:no-repeat scroll right center rgb(221, 221, 221);">
                            <span class="textos clearfix">
                                <span class="titulo">Enlaces de Interes</span>
                            </span>
                        </a>
                    </div> 
                    <table class="artist-photo">
                        <tr>

                            <td class="">
                                <div>
                                    <a href="/go?link=https://www.google.com.pe"> <img class="img-iconos"
                                                                                       src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/google.png">
                                    </a>
                                </div>
                            </td>
                            <td class="">
                                <div>
                                    <a href="/go?link=https://m.facebook.com/"> <img class="img-iconos"
                                                                                     src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/facebook.png">
                                    </a>
                                </div>
                            </td>
                            <td class="">
                                <div>
                                    <a href="/go?link=https://mobile.twitter.com/"> <img class="img-iconos"
                                                                                         src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/twitter.png">
                                    </a>
                                </div>
                            </td>
                            <td class="">
                                <div>
                                    <a href="/go?link=https://www.youtube.com"> <img class="img-iconos"
                                                                                     src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/youtube.png">
                                    </a>
                                </div>
                            </td>
                            <td class="">
                                <div>
                                    <a href="/go?link=http://elcomercio.pe/movil/"> <img class="img-iconos"
                                                                                         src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/comercio.png">
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="">
                                <div>
                                    <a href="https://mail.google.com/"> <img class="img-iconos"
                                                                             src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/gmail.png">
                                    </a>
                                </div>
                            </td>
                            <td class="">
                                <div>
                                    <a href="/go?link=https://login.live.com/"> <img class="img-iconos"
                                                                                     src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/hotmail.png">
                                    </a>
                                </div>
                            </td>
                            <td class="">
                                <div>
                                    <a href="http://es.m.wikipedia.org/wiki/Main_Page"> <img class="img-iconos"
                                                                                             src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/wikipedia.png">
                                    </a>
                                </div>
                            </td>
                            <td class="">
                                <div>
                                    <a href="/go?link=https://www.linkedin.com/uas/login"> <img class="img-iconos"
                                                                                                src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/linkedin.png">
                                    </a>
                                </div>
                            </td>
                            <td class="">
                                <div>
                                    <a href="/go?link=http://www.terra.com/"> <img class="img-iconos"
                                                                                   src="<?php echo MEDIA_URL ?>img/portalwap/basico360/servicios/cartelera.png">
                                    </a>
                                </div>
                            </td>
                        </tr>
                    </table>
                    <br>
                    <!----------------MUSICA TOP------------------------------------->
                    <div id="cabecera-listado" class="clearfix">
                        <a id="cabecera_paso1" class="paso primero seleccionado" href="" style="background:no-repeat scroll right center rgb(221, 221, 221);">
                            <span class="textos clearfix">
                                <span class="bullet">1</span>
                                <span class="titulo">M&uacute;sica Top</span>
                            </span>
                        </a>
                    </div> 
                    <div class="menuPrincipal clearfix">
                        <?php
                        $i = 0;
                        foreach ($this->SoapMusica as $item):
                            $i++;
                            ?>
                            <div id="medium">
                                <a href="/go?link=http://entel.bip.pe/pe/fulltracks/?catalogo=<?= strtoupper($item->catalogo) ?>">
                                    <?php if ($i == 1) { ?>
                                        <span class="puestoOne"><p><?= $i ?></p></span>
                                    <?php } else { ?>
                                        <span class="puesto"><p><?= $i ?></p></span>
                                    <?php } ?>
                                    <div class="menu" >
                                        <?php
                                        $nombre_fichero = APPLICATION_PATH . '/../public/static/img/portalwap/basico360/musica/' . $item->catalogo . '.jpg';
                                        if (file_exists($nombre_fichero)) {
                                            ?>
                                            <img src="<?php echo MEDIA_URL ?>img/portalwap/basico360/musica/<?= $item->catalogo ?>.jpg"  height="47" border="0" />
                                        <?php } else {
                                            ?>
                                            <img src="<?php echo MEDIA_URL ?>img/portalwap/basico360/musica/default.gif" width="64" height="47" border="0" />

                                        <?php }
                                        ?> 
                                        <p><?= strtoupper($item->tema) ?></p>
                                        <br><span ><?= $item->artista ?></span>
                                    </div>
                                </a>
                            </div>
                            <?php
                        endforeach;
                        ?>
                    </div>
                    <div id="cabecera-listado" class="clearfix" style="background-color:#F68E1F;height: 19px ">
                        <a  id="cabecera_paso1" class="paso primero seleccionado" href="/go?link=http://entel.bip.pe/fulltracks">
                            <span style="text-decoration: underline;color:white;float: right;margin-right:10px">Suscr&iacute;bete</span>
                        </a>
                    </div>

                    <br>
                    <!----------------TONOS------------------------------------->
                    <div id="cabecera-listado" class="clearfix">
                        <a id="cabecera_paso1" class="paso primero seleccionado" href="#" style="background:no-repeat scroll right center rgb(221, 221, 221); ">
                            <span class="textos clearfix">
                                <span class="bullet">2</span>
                                <span class="titulo">Tonos</span>
                            </span>
                        </a></div>
                    <div class="menuPrincipal clearfix">
                        <?php
                        $i = 0;
                        foreach ($this->SoapTonos as $item):
                            $i++;
                            ?>
                            <div id="medium">
                                <a href="/go?link=http://entel.bip.pe/pe/realtones/?catalogo=<?= strtoupper($item->catalogo) ?>">
                                    <?php if ($i == 1) { ?>
                                        <span class="puestoOne"><p><?= $i ?></p></span>
                                    <?php } else { ?>
                                        <span class="puesto"><p><?= $i ?></p></span>
                                    <?php } ?>
                                    <div class="menu" >
                                        <?php
                                        $nombre_fichero = APPLICATION_PATH . '/../public/static/img/portalwap/basico360/tonos/' . $item->catalogo . '.jpg';
                                        if (file_exists($nombre_fichero)) {
                                            ?>
                                            <img src="<?php echo MEDIA_URL ?>img/portalwap/basico360/tonos/<?= $item->catalogo ?>.jpg"  height="47" border="0" />
                                        <?php } else {
                                            ?>
                                            <img src="<?php echo MEDIA_URL ?>img/portalwap/basico360/tonos/default.gif" width="64" height="47" border="0" />

                                        <?php }
                                        ?> 
                                        <p><?= strtoupper($item->tema) ?></p>
                                        <br><span ><?= $item->artista ?></span>
                                    </div>
                                </a>
                            </div>
                            <?php
                        endforeach;
                        ?>
                    </div> 
                    <div id="cabecera-listado" class="clearfix" style="background-color:#F68E1F;height: 19px ">
                        <a  id="cabecera_paso1" class="paso primero seleccionado" href="/go?link=http://entel.bip.pe/realtones">
                            <span style="text-decoration: underline;color:white;float: right;margin-right:10px">Suscr&iacute;bete</span>
                        </a>
                    </div>
                    <br>
                </div>
            </div>
        </div>
    </div>
    <?php
    if (empty($this->usuario) && !isset($this->usuario) && $this->perfil != '240') {
        if (isset($this->numero) && $this->numero != '') {
            ?>
            <script>
                $(document).ready(function () {
                    centraVentana();
                    muestraVentana();
                    $("#ventanaPopup1Cerrar").click(function () {
                        ocultaVentana();
                    });
                    $("#ventanaPopup1Fondo").click(function () {
                        ocultaVentana();
                    });
                });

                function centraVentana() {
                    var windowWidth = document.documentElement.clientWidth;
                    var windowHeight = document.documentElement.clientHeight;
                    var popupHeight = $("#ventanaPopup1").height();
                    var popupWidth = $("#ventanaPopup1").width();
                    $("#ventanaPopup1").css({
                        "position": "absolute",
//                                    "top": windowHeight / 2 - popupHeight / 2,
//                                    "left": windowWidth / 2 - popupWidth / 2
                    });

                    $("#ventanaPopup1Fondo").css({
                        "height": windowHeight
                    });
                }
                function ocultaVentana() {
                    $("#ventanaPopup1Fondo").fadeOut("slow");
                    $("#ventanaPopup1").fadeOut("slow");
                }

                function muestraVentana() {
                    $("#ventanaPopup1Fondo").css({
                        "opacity": "0.7"
                    });
                    $("#ventanaPopup1Fondo").fadeIn("slow");
                    $("#ventanaPopup1").fadeIn("slow");
                }
            </script>
            <?php
        }}
        ?>
<style type="text/css">
    #ventanaPopup1Fondo{
        display:none;
        position:fixed;
        _position:absolute; /* caso especial para IE 6*/
        height:100%;
        width:100%;
        top:0;
        left:0;
        background:#000000;
        z-index:1;
    }
    #ventanaPopup1{
        border:4px solid #0154A0;
        top:20px;
        margin: 0px 18px 10px 23px;
        display:none;
        position:fixed;
        _position:absolute; /* caso especial para IE 6*/
        /*height:384px;*/
        /*width:408px;*/
        background:#FFFFFF;
        z-index:2;
        padding:12px;
        font-size:13px;
        /*border:5px solid #888888;*/

        /*border-radius:10px;*/
        -moz-border-radius:10px;
    }
    #ventanaPopup1Cerrar{
        font-size:14px;
        line-height:14px;
        right:2px;
        top:4px;
        position:absolute;
        color:#6fa5fd;
        font-weight:700;
        display:block;
        cursor: hand;
        
    }
    #form
    {

        margin:auto;
        font-family: sans-serif;
        /*box-shadow: 5px 5px 5px #888888;*/
        padding: 2px 20px 20px  20px;
        /*border:4px solid #27748A;*/
    }
    #form h2
    {
        color:#27748A;
        font-size:35px;
        margin:0;
    }
    #form p
    {
        font-size:15px;
        color:#222222;
    }

    #form div
    {
        margin-top:10px;
    }
    #form input, textarea, button,select,radio
    {
        width:100%;
        border:2px solid #EBEBEB;
        padding:3px 5px;
    }
    #form label
    {
        font-weight:bold;
        font-size:12px;
        color:#0154A0;
    }

    #form button
    {
        background-color: #FF6702;
        border:2px solid #FF6702;
        color: white;
        cursor:pointer;
    }
    #form button:hover
    {
        background-color: #0154A0;
        border:2px solid #0154A0;
        color: white;
    }
    .dia{width: 50px; float: left; margin-right: 5px;list-style:none;}
    .mes{width: 80px; float: left; margin-right: 5px;list-style:none;}
    .ano{width: 60px; float: left;list-style:none;}
</style>
