<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                <!----------------BANNER DE DEDICATORIA------------------------------------->
                <?php $this->getMesseger(); ?>
                <?php if (isset($this->usuario) && !empty($this->usuario)) { ?>
                <br>
                <table class="artist-photo">
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: #EBEBEB;">
                            <div style="padding-left: 5px;float: left;color: #0154A0" >
                                hola [ <?php echo  ' '. $this->usuario ?>  ]
                            </div>
                        </td>
                    </tr>  </table>

            <?php } ?>
                <div>
                    <a href="/go?link=http://entel.bip.pe/pe/realtones">
                        <img width="100%" height="50px" src="<?php echo MEDIA_URL ?>img/portalwap/basico240/slider/banner_tonos_nextel.gif">
                    </a>
                </div>

                <div>
                    <a href="/go?link=http://entel.bip.pe/pe/fulltracks">
                        <img width="100%" height="50px" src="<?php echo MEDIA_URL ?>img/portalwap/basico240/slider/banner-musica-nextel.gif">
                    </a>
                </div>
                <div> 
                    <a href="/go?link=/dedicatoria">
                        <img width="100%" height="50px" src="<?php echo MEDIA_URL ?>img/portalwap/basico240/slider/banner_dedicatorias_nextel.gif">
                    </a>
                </div>
                <div> 
                    <a href="/go?link=http://mobile.terra.com/sc/pe/suscfutentel/">
                        <img width="100%" src="<?php echo MEDIA_URL ?>img/portalwap/basico240/slider/180x54.gif">
                    </a>
                </div>
                <!----------------BUSCADORES DESTACADOS------------------------------------->
                
                <table class="artist-photo">
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: #0073ae;">
                            <div class="artist-text" style="color: white" >
                                <div class="title-img">
                                    <a class="text-title" style="color: white;font-size:15px"
                                       href="#">ENLACES DE INTERES
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=https://www.google.com.pe">Google
                                    </a>
                                </div>
                            </div>
                        </td>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=https://m.facebook.com/">Facebook
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=https://mobile.twitter.com/">Twitter
                                    </a>
                                </div>
                            </div>
                        </td>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=https://www.youtube.com">Youtube
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=http://elcomercio.pe/movil/">El Comercio
                                    </a>
                                </div>
                            </div>
                        </td>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=https://mail.google.com/">Gmail
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=https://login.live.com/">Hotmail
                                    </a>
                                </div>
                            </div>
                        </td>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=http://es.m.wikipedia.org/wiki/Main_Page">Wikipedia
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=https://www.linkedin.com/uas/login">Linkedin
                                    </a>
                                </div>
                            </div>
                        </td>
                        <td class="artist">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title"
                                       href="/go?link=http://www.terra.com/">Cartelera
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>

                </table>




                <br>
                <!----------------MUSICA TOP------------------------------------->

                <table class="artist-photo">
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: #0073ae">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="color: white;font-size:15px"
                                       href="#">MUSICA TOP
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php
                    $i = 0;
                    foreach ($this->SoapMusica as $item):
                        $i++;
                        ?>
                        <tr>
                            <td class="artist">

                                <div class="artist-text" style="text-align:left;">
                                    <div class="title-img">
                                        <a class="text-title"
                                           href="/go?link=http://entel.bip.pe/pe/fulltracks/?catalogo=<?= strtoupper($item->catalogo) ?>"><?= strtoupper($item->tema) ?>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr> 
                        <?php
                    endforeach;
                    ?>
                    <tr>
                        <td class="artist"  colspan=5 style="background-color:#F68E1F;height: 12px ">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="text-decoration: underline;float: right;color: white;font-size:18px"
                                       href="/go?link=http://entel.bip.pe/pe/fulltracks">Suscr&iacute;bete
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <br>
                <!----------------TONOS------------------------------------->

                <table class="artist-photo">
                    <tr>
                        <td class="artist"  colspan=2 style="background-color: #0073ae">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="color: white;font-size:15px"
                                       href="#">TONOS
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <?php
                    $i = 0;
                    foreach ($this->SoapTonos as $item):
                        $i++;
                        ?>
                        <tr>
                            <td class="artist">

                                <div class="artist-text" style="text-align:left;">
                                    <div class="title-img">
                                        <a class="text-title"
                                           href="/go?link=http://entel.bip.pe/pe/realtones/?catalogo=<?= strtoupper($item->catalogo) ?>"><?= strtoupper($item->tema) ?>
                                        </a>
                                    </div>
                                </div>
                            </td>
                        </tr> 
                        <?php
                    endforeach;
                    ?>
                    <tr>
                        <td class="artist"  colspan=5 style="background-color:#F68E1F;height: 12px ">
                            <div class="artist-text">
                                <div class="title-img">
                                    <a class="text-title" style="text-decoration: underline;float: right;color: white;font-size:18px"
                                       href="/go?link=http://entel.bip.pe/pe/realtones">Suscr&iacute;bete
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>

            </div>
        </div>
    </div>
</div>
<br>
<!--Footer-->                                

