<div id="prueba_master" class="wlp-bighorn-book">
    <div class="wlp-bighorn-book-content">
        <div class="wlp-bighorn-layout wlp-bighorn-layout-flow">
            <div class="wlp-bighorn-layout-cell wlp-bighorn-layout-flow-horizontal wlp-bighorn-layout-flow-first" style="width: 100%">
                <br>
                <div id="ventanaPopup1">
                 <form id="form" action="/registro" method="post">
                            
                            <h2 style="text-align:center; color:#0154A0;">PERSONALIZA TU CUENTA</h2>
                            <div>
                                <label for='name'>Nombre</label>
                                <input type='text' name='nombres' placeholder='Tu nombre' required />
                            </div>
                            <div>
                                <label for='tel'>Fecha de Nacimiento</label><br>
                                <li  class="dia"><label for="Dia"></label><select class="iselect2 selectFecha2" name="dia" id="Dia">
                                        <option value="01">1</option>
                                        <option value="02">2</option>
                                        <option value="03">3</option>
                                        <option value="04">4</option>
                                        <option value="05">5</option>
                                        <option value="06">6</option>
                                        <option value="07">7</option>
                                        <option value="08">8</option>
                                        <option value="09">9</option>
                                        <option value="10">10</option>
                                        <option value="11">11</option>
                                        <option value="12">12</option>
                                        <option value="13">13</option>
                                        <option value="14">14</option>
                                        <option value="15">15</option>
                                        <option value="16">16</option>
                                        <option value="17">17</option>
                                        <option value="18">18</option>
                                        <option value="19">19</option>
                                        <option value="20">20</option>
                                        <option value="21">21</option>
                                        <option value="22">22</option>
                                        <option value="23">23</option>
                                        <option value="24">24</option>
                                        <option value="25">25</option>
                                        <option value="26">26</option>
                                        <option value="27">27</option>
                                        <option value="28">28</option>
                                        <option value="29">29</option>
                                        <option value="30">30</option>
                                        <option value="31">31</option>
                                    </select></li>
                                <li class="mes"><label for="Mes"></label><select class="iselect3" name="mes" id="Mes">
                                        <option value="01">Enero</option>
                                        <option value="02">Febrero</option>
                                        <option value="03">Marzo</option>
                                        <option value="04">Abril</option>
                                        <option value="05">Mayo</option>
                                        <option value="06">Junio</option>
                                        <option value="07">Julio</option>
                                        <option value="08">Agosto</option>
                                        <option value="09">Septiembre</option>
                                        <option value="10">Octubre</option>
                                        <option value="11">Noviembre</option>
                                        <option value="12">Diciembre</option>   
                                    </select></li>
                                <li class="ano"><label for="Ano"></label><select class="iselect3" name="anio" id="Ano">
                                        <option value='2006'>2006</option>
                                        <option value='2005'>2005</option>
                                        <option value='2004'>2004</option>
                                        <option value='2003'>2003</option>
                                        <option value='2002'>2002</option>
                                        <option value='2001'>2001</option>
                                        <option value='2000'>2000</option>
                                        <option value='1999'>1999</option>
                                        <option value='1998'>1998</option>
                                        <option value='1997'>1997</option>
                                        <option value='1996'>1996</option>
                                        <option value='1995'>1995</option>
                                        <option value='1994'>1994</option>
                                        <option value='1993'>1993</option>
                                        <option value='1992'>1992</option>
                                        <option value='1991'>1991</option>
                                        <option value='1990'>1990</option>
                                        <option value='1989'>1989</option>
                                        <option value='1988'>1988</option>
                                        <option value='1987'>1987</option>
                                        <option value='1986'>1986</option>
                                        <option value='1985'>1985</option>
                                        <option value='1984'>1984</option>
                                        <option value='1983'>1983</option>
                                        <option value='1982'>1982</option>
                                        <option value='1981'>1981</option>
                                        <option value='1980'>1980</option>
                                        <option value='1979'>1979</option>
                                        <option value='1978'>1978</option>
                                        <option value='1977'>1977</option>
                                        <option value='1976'>1976</option>
                                        <option value='1975'>1975</option>
                                        <option value='1974'>1974</option>
                                        <option value='1973'>1973</option>
                                        <option value='1972'>1972</option>
                                        <option value='1971'>1971</option>
                                        <option value='1970'>1970</option>
                                        <option value='1969'>1969</option>
                                        <option value='1968'>1968</option>
                                        <option value='1967'>1967</option>
                                        <option value='1966'>1966</option>
                                        <option value='1965'>1965</option>
                                        <option value='1964'>1964</option>
                                        <option value='1963'>1963</option>
                                        <option value='1962'>1962</option>
                                        <option value='1961'>1961</option>
                                        <option value='1960'>1960</option>
                                        <option value='1959'>1959</option>
                                        <option value='1958'>1958</option>
                                        <option value='1957'>1957</option>
                                        <option value='1956'>1956</option>
                                    </select></li><br>
                            </div>
                            <br>
                            <div>
                                <label for='tel'>Género</label><br>
                                <input type="radio" name="sexo" value="masculino" checked>M
                                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                                <input type="radio" name="sexo" value="femenino">F
                            </div>
                            <div>
                                <label for='url'>Ciudad</label>
                                <select name="ciudad">
                                    <option value="0">-Seleccione-</option>
                                    <option value="1">Amazonas</option>
                                    <option value="2">Ancash</option>
                                    <option value="3">Apurimac</option>
                                    <option value="4">Arequipa</option>
                                    <option value="5">Ayacucho</option>
                                    <option value="6">Cajamarca</option>
                                    <option value="7">Callao</option>
                                    <option value="8">Cusco</option>
                                    <option value="9">Huancavelica</option>
                                    <option value="10">Huanuco</option>
                                    <option value="11">Ica</option>
                                    <option value="12">Junin</option>
                                    <option value="13">La Libertad</option>
                                    <option value="14">Lambayeque</option>
                                    <option value="15">Lima</option>
                                    <option value="16">Loreto</option>
                                    <option value="17">Madre De Dios</option>
                                    <option value="18">Moquegua</option>
                                    <option value="19">Pasco</option>
                                    <option value="20">Piura</option>
                                    <option value="21">Puno</option>
                                    <option value="22"> San Martin</option>
                                    <option value="23">Tacna</option>
                                    <option value="24">Tumbes</option>
                                    <option value="25">Ucayali</option>
                                </select> 
                            </div>
                            <div>
                                <button type='submit'>Registrarme</button>
                            </div>
                        </form>
                         </div>
            </div>
        </div>
    </div>
</div>

<style type="text/css">
   
    #ventanaPopup1{
        border:3px solid #0154A0;
        margin: 0px 5px 10px 5px;
        /*height:384px;*/
        /*width:408px;*/
        background:#FFFFFF;
        z-index:2;
        padding:6px;
        font-size:13px;
        /*border:5px solid #888888;*/

        /*border-radius:10px;*/
        -moz-border-radius:10px;
    }
 
    #form
    {
        margin:auto;
        font-family: sans-serif;
        /*box-shadow: 5px 5px 5px #888888;*/
        padding: 2px 20px 20px  20px;
        /*border:4px solid #27748A;*/
    }
    #form h2
    {
        color:#27748A;
        font-size:14px;
        margin:0;
    }
    #form p
    {
        font-size:15px;
        color:#222222;
    }

    #form div
    {
        margin-top:10px;
    }
    #form input, textarea, button,select,radio
    {
        width:100%;
        border:2px solid #EBEBEB;
        padding:3px 5px;
    }
    #form label
    {
        font-weight:bold;
        font-size:12px;
        color:#0154A0;
    }

    #form button
    {
        background-color: #FF6702;
        border:2px solid #FF6702;
        color: white;
        cursor:pointer;
    }
    #form button:hover
    {
        background-color: #0154A0;
        border:2px solid #0154A0;
        color: white;
    }
    .dia{width: 50px; float: left; margin-right: 5px;list-style:none;}
    .mes{width: 80px; float: left; margin-right: 5px;list-style:none;}
    .ano{width: 60px; float: left;list-style:none;}
</style>